INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (1, N'Afganistan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (2, N'Albania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (3, N'Algieria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (4, N'Andora')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (5, N'Angola')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (6, N'Antigua i Barbuda')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (7, N'Arabia Saudyjska')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (8, N'Argentyna')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (9, N'Armenia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (10, N'Australia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (11, N'Austria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (12, N'Azerbejdzan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (13, N'Bahamy')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (14, N'Bahrajn')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (15, N'Bangladesz')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (16, N'Barbados')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (17, N'Belgia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (18, N'Belize')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (19, N'Benin')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (20, N'Bhutan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (21, N'Bialorus')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (22, N'Birma')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (23, N'Boliwia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (24, N'Bosnia i Hercegowina')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (25, N'Botswana')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (26, N'Brazylia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (27, N'Brunei')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (28, N'Bulgaria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (29, N'Burkina Faso')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (30, N'Burundi')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (31, N'Chile')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (32, N'Chiny')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (33, N'Chorwacja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (34, N'Cypr')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (35, N'Czad')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (36, N'Czarnogóra')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (37, N'Czechy')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (38, N'Dania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (39, N'Demokratyczna Republika Konga')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (40, N'Dominika')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (41, N'Dominikana')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (42, N'Dzibuti')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (43, N'Egipt')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (44, N'Ekwador')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (45, N'Erytrea')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (46, N'Estonia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (47, N'Etiopia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (48, N'Fidzi')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (49, N'Filipiny')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (50, N'Finlandia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (51, N'Francja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (52, N'Gabon')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (53, N'Gambia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (54, N'Ghana')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (55, N'Grecja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (56, N'Grenada')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (57, N'Gruzja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (58, N'Gujana')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (59, N'Gwatemala')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (60, N'Gwinea')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (61, N'Gwinea Bissau')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (62, N'Gwinea Równikowa')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (63, N'Haiti')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (64, N'Hiszpania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (65, N'Holandia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (66, N'Honduras')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (67, N'Indie')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (68, N'Indonezja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (69, N'Irak')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (70, N'Iran')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (71, N'Irlandia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (72, N'Islandia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (73, N'Izrael')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (74, N'Jamajka')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (75, N'Japonia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (76, N'Jemen')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (77, N'Jordania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (78, N'Kambodza')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (79, N'Kamerun')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (80, N'Kanada')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (81, N'Katar')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (82, N'Kazachstan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (83, N'Kenia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (84, N'Kirgistan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (85, N'Kiribati')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (86, N'Kolumbia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (87, N'Komory')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (88, N'Kongo')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (89, N'Korea Poludniowa')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (90, N'Korea Pólnocna')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (91, N'Kostaryka')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (92, N'Kuba')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (93, N'Kuwejt')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (94, N'Laos')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (95, N'Lesotho')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (96, N'Liban')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (97, N'Liberia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (98, N'Libia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (99, N'Liechtenstein')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (100, N'Litwa')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (101, N'Luksemburg')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (102, N'Lotwa')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (103, N'Macedonia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (104, N'Madagaskar')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (105, N'Malawi')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (106, N'Malediwy')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (107, N'Malezja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (108, N'Mali')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (109, N'Malta')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (110, N'Maroko')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (111, N'Mauretania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (112, N'Mauritius')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (113, N'Meksyk')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (114, N'Mikronezja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (115, N'Moldawia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (116, N'Monako')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (117, N'Mongolia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (118, N'Mozambik')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (119, N'Namibia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (120, N'Nauru')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (121, N'Nepal')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (122, N'Niemcy')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (123, N'Niger')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (124, N'Nigeria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (125, N'Nikaragua')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (126, N'Norwegia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (127, N'Nowa Zelandia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (128, N'Oman')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (129, N'Pakistan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (130, N'Palau')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (131, N'Panama')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (132, N'Papua-Nowa Gwinea')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (133, N'Paragwaj')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (134, N'Peru')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (135, N'Polska')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (136, N'Portugalia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (137, N'Republika Poludniowej Afryki')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (138, N'Republika Srodkowoafrykanska')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (139, N'Republika Zielonego Przyladka')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (140, N'Rosja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (141, N'Rumunia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (142, N'Rwanda')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (143, N'Saint Kitts i Nevis')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (144, N'Saint Lucia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (145, N'Saint Vincent i Grenadyny')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (146, N'Salwador')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (147, N'Samoa')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (148, N'San Marino')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (149, N'Senegal')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (150, N'Serbia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (151, N'Seszele')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (152, N'Sierra Leone')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (153, N'Singapur')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (154, N'Slowacja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (155, N'Slowenia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (156, N'Somalia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (157, N'Sri Lanka')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (158, N'Stany Zjednoczone')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (159, N'Suazi')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (160, N'Sudan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (161, N'Surinam')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (162, N'Syria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (163, N'Szwajcaria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (164, N'Szwecja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (165, N'Tadzykistan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (166, N'Tajlandia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (167, N'Tanzania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (168, N'Timor Wschodni')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (169, N'Togo')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (170, N'Tonga')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (171, N'Trynidad i Tobago')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (172, N'Tunezja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (173, N'Turcja')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (174, N'Turkmenistan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (175, N'Tuvalu')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (176, N'Uganda')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (177, N'Ukraina')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (178, N'Urugwaj')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (179, N'Uzbekistan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (180, N'Vanuatu')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (181, N'Watykan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (182, N'Wenezuela')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (183, N'Wegry')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (184, N'Wielka Brytania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (185, N'Wietnam')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (186, N'Wlochy')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (187, N'Wybrzeze Kosci Sloniowej')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (188, N'Wyspy Marshalla')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (189, N'Wyspy Salomona')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (191, N'Zambia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (192, N'Zimbabwe')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (193, N'Zjednoczone Emiraty Arabskie')

