INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (11, N'Wobler')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (12, N'Wahadłówka')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (13, N'Obrotówka')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (14, N'Cykada')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (15, N'Powierzchniowiec')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (16, N'Twister')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (17, N'Ripper')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (18, N'Inna silikonowa')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (19, N'Jig\kogut')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (20, N'Nimfa')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (21, N'Sucha mucha')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (22, N'Streamer')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (23, N'Mokra mucha')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (24, N'Naturalna')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (25, N'Kulka proteinowa')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (26, N'Białe robaki')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (27, N'Czerwone robaki')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (28, N'Pellet')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (29, N'Kukurydza')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (30, N'Pęcak')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (31, N'Pszenica')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (32, N'Żywiec')
INSERT INTO [dbo].[LureBait] ([ID], [Name]) VALUES (33, N'Martwa rybka')
