INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (1, N'Amur')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (2, N'Belona')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (3, N'Boleń')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (4, N'Brzana')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (5, N'Dorsz')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (6, N'Głowacica')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (7, N'Jaź')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (8, N'Jelec')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (9, N'Karaś srebrzysty')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (10, N'Karaś złocisty')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (11, N'Karp')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (12, N'Kleń')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (13, N'Leszcz')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (14, N'Lin')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (15, N'Lipień')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (16, N'Łosoś')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (17, N'Miętus')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (18, N'Okoń')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (19, N'Płoć')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (20, N'Pstrąg potokowy')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (21, N'Pstrąg tęczowy')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (22, N'Pstrąg źródlany')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (23, N'Sandacz')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (24, N'Sieja')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (25, N'Sum')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (26, N'Świnka')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (27, N'Szczupak')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (28, N'Tołpyga')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (29, N'Troć')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (30, N'Węgorz')
INSERT INTO [dbo].[Specie] ([ID], [Name]) VALUES (31, N'Wzdręga')
