CREATE TABLE [dbo].[Fish] (
    [ID]               INT           IDENTITY (1, 1) NOT NULL,
    [SpecieID]         TINYINT       NOT NULL,
    [Length]           SMALLINT      NOT NULL,
    [Weight]           SMALLINT      NULL,
    [CatchDate]        DATETIME      NOT NULL,
    [WaterTemp]        SMALLINT      NULL,
    [AirTemp]          SMALLINT      NULL,
    [WindDirID]        TINYINT       NULL,
    [WindSpeed]        TINYINT       NULL,
    [MoonPhase]        TINYINT       NULL,
    [Pressure]         SMALLINT      NULL,
    [PressureChangeID] TINYINT       NULL,
    [WaterLevelID]     TINYINT       NULL,
    [CloudsID]         TINYINT       NULL,
    [FisheryTypeID]    TINYINT       NOT NULL,
    [CountryID]        TINYINT       NOT NULL,
    [PrecipitationID]  TINYINT       NULL,
    [AnglerID]         INT           NOT NULL,
    [StatusID]         TINYINT       DEFAULT ((1)) NOT NULL,
    [MethodID]         TINYINT       NOT NULL,
    [LureBaitID]       TINYINT       NULL,
    [LureBaitDesc]     NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Fish_ToAngler] FOREIGN KEY ([AnglerID]) REFERENCES [dbo].[Angler] ([ID]),
    CONSTRAINT [FK_Fish_ToClouds] FOREIGN KEY ([CloudsID]) REFERENCES [dbo].[Clouds] ([ID]),
    CONSTRAINT [FK_Fish_ToCountry] FOREIGN KEY ([CountryID]) REFERENCES [dbo].[Country] ([ID]),
    CONSTRAINT [FK_Fish_ToFisheryType] FOREIGN KEY ([FisheryTypeID]) REFERENCES [dbo].[FisheryType] ([ID]),
    CONSTRAINT [FK_Fish_ToFishStatus] FOREIGN KEY ([StatusID]) REFERENCES [dbo].[FishStatus] ([ID]),
    CONSTRAINT [FK_Fish_ToLureBait] FOREIGN KEY ([LureBaitID]) REFERENCES [dbo].[LureBait] ([ID]),
    CONSTRAINT [FK_Fish_ToMethod] FOREIGN KEY ([MethodID]) REFERENCES [dbo].[Method] ([ID]),
    CONSTRAINT [FK_Fish_ToPrecipitation] FOREIGN KEY ([PrecipitationID]) REFERENCES [dbo].[Precipitation] ([ID]),
    CONSTRAINT [FK_Fish_ToPressureChange] FOREIGN KEY ([PressureChangeID]) REFERENCES [dbo].[PressureChange] ([ID]),
    CONSTRAINT [FK_Fish_ToSpecie] FOREIGN KEY ([SpecieID]) REFERENCES [dbo].[Specie] ([ID]),
    CONSTRAINT [FK_Fish_ToWaterLevel] FOREIGN KEY ([WaterLevelID]) REFERENCES [dbo].[WaterLevel] ([ID]),
    CONSTRAINT [FK_Fish_ToWindDirection] FOREIGN KEY ([WindDirID]) REFERENCES [dbo].[WindDirection] ([ID])
);

